// Code generated by goctl. DO NOT EDIT.
// Source: video-rpc.proto

package videoclient

import (
	"context"

	"go_code/Doul/app/video/cmd/rpc/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	StreamReq  = video.StreamReq
	StreamResp = video.StreamResp

	Video interface {
		Greet(ctx context.Context, in *StreamReq, opts ...grpc.CallOption) (*StreamResp, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

func (m *defaultVideo) Greet(ctx context.Context, in *StreamReq, opts ...grpc.CallOption) (*StreamResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.Greet(ctx, in, opts...)
}
