// Code generated by goctl. DO NOT EDIT.
// Source: video-rpc.proto

package videoclient

import (
	"context"

	"go_code/Doul/app/video/cmd/rpc/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FavoriteListReq  = video.FavoriteListReq
	FavoriteListResp = video.FavoriteListResp
	FeedReq          = video.FeedReq
	FeedResp         = video.FeedResp
	PublishListReq   = video.PublishListReq
	PublishListResp  = video.PublishListResp
	UserPO           = video.UserPO
	VideoPO          = video.VideoPO

	Video interface {
		Feed(ctx context.Context, in *FeedReq, opts ...grpc.CallOption) (*FeedResp, error)
		PublishList(ctx context.Context, in *PublishListReq, opts ...grpc.CallOption) (*PublishListResp, error)
		FavoriteList(ctx context.Context, in *FavoriteListReq, opts ...grpc.CallOption) (*FavoriteListResp, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

func (m *defaultVideo) Feed(ctx context.Context, in *FeedReq, opts ...grpc.CallOption) (*FeedResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.Feed(ctx, in, opts...)
}

func (m *defaultVideo) PublishList(ctx context.Context, in *PublishListReq, opts ...grpc.CallOption) (*PublishListResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.PublishList(ctx, in, opts...)
}

func (m *defaultVideo) FavoriteList(ctx context.Context, in *FavoriteListReq, opts ...grpc.CallOption) (*FavoriteListResp, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.FavoriteList(ctx, in, opts...)
}
