// Code generated by goctl. DO NOT EDIT.
// Source: video-rpc.proto

package server

import (
	"context"

	"go_code/Doul/app/video/cmd/rpc/internal/logic"
	"go_code/Doul/app/video/cmd/rpc/internal/svc"
	"go_code/Doul/app/video/cmd/rpc/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServer) Greet(ctx context.Context, in *video.StreamReq) (*video.StreamResp, error) {
	l := logic.NewGreetLogic(ctx, s.svcCtx)
	return l.Greet(in)
}
