// Code generated by goctl. DO NOT EDIT.
// Source: video-rpc.proto

package server

import (
	"context"

	"go_code/Doul/app/video/cmd/rpc/internal/logic"
	"go_code/Doul/app/video/cmd/rpc/internal/svc"
	"go_code/Doul/app/video/cmd/rpc/pb"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServer) Feed(ctx context.Context, in *pb.FeedReq) (*pb.FeedResp, error) {
	l := logic.NewFeedLogic(ctx, s.svcCtx)
	return l.Feed(in)
}

func (s *VideoServer) PublishList(ctx context.Context, in *pb.PublishListReq) (*pb.PublishListResp, error) {
	l := logic.NewPublishListLogic(ctx, s.svcCtx)
	return l.PublishList(in)
}

func (s *VideoServer) FavoriteList(ctx context.Context, in *pb.FavoriteListReq) (*pb.FavoriteListResp, error) {
	l := logic.NewFavoriteListLogic(ctx, s.svcCtx)
	return l.FavoriteList(in)
}

func (s *VideoServer) Like(ctx context.Context, in *pb.LikeReq) (*pb.LikeResp, error) {
	l := logic.NewLikeLogic(ctx, s.svcCtx)
	return l.Like(in)
}
