// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: security.proto

package security

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SecurityClient is the client API for Security service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecurityClient interface {
	Check(ctx context.Context, in *CheckLegaContentReq, opts ...grpc.CallOption) (*CheckLegalContentResp, error)
}

type securityClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityClient(cc grpc.ClientConnInterface) SecurityClient {
	return &securityClient{cc}
}

func (c *securityClient) Check(ctx context.Context, in *CheckLegaContentReq, opts ...grpc.CallOption) (*CheckLegalContentResp, error) {
	out := new(CheckLegalContentResp)
	err := c.cc.Invoke(ctx, "/security.Security/check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityServer is the server API for Security service.
// All implementations must embed UnimplementedSecurityServer
// for forward compatibility
type SecurityServer interface {
	Check(context.Context, *CheckLegaContentReq) (*CheckLegalContentResp, error)
	mustEmbedUnimplementedSecurityServer()
}

// UnimplementedSecurityServer must be embedded to have forward compatible implementations.
type UnimplementedSecurityServer struct {
}

func (UnimplementedSecurityServer) Check(context.Context, *CheckLegaContentReq) (*CheckLegalContentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedSecurityServer) mustEmbedUnimplementedSecurityServer() {}

// UnsafeSecurityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityServer will
// result in compilation errors.
type UnsafeSecurityServer interface {
	mustEmbedUnimplementedSecurityServer()
}

func RegisterSecurityServer(s grpc.ServiceRegistrar, srv SecurityServer) {
	s.RegisterService(&Security_ServiceDesc, srv)
}

func _Security_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLegaContentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/security.Security/check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServer).Check(ctx, req.(*CheckLegaContentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Security_ServiceDesc is the grpc.ServiceDesc for Security service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Security_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "security.Security",
	HandlerType: (*SecurityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "check",
			Handler:    _Security_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "security.proto",
}
