// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginRes struct {
	UserId int64  `json:"user_id,omitempty"`
	Token  string `json:"token"`
}

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type RegisterRes struct {
	UserId int64  `json:"user_id,omitempty"`
	Token  string `json:"token"`
}

type InfoRes struct {
	FollowCount   int64  `json:"follow_count"`   // 关注总数
	FollowerCount int64  `json:"follower_count"` // 粉丝总数
	ID            int64  `json:"id"`             // 用户id
	IsFollow      bool   `json:"is_follow"`      // true-已关注，false-未关注
	Name          string `json:"name"`
}

type InfoReq struct {
	UserId int64 `form:"user_id,omitempty"`
}
