// Code generated by goctl. DO NOT EDIT.
package types

type CommonResp struct {
	Code uint32 `json:"status_code" default:"0"`
	Msg  string `json:"status_msg" default:"OK"`
}

type UserPO struct {
	FollowCount   int64  `json:"follow_count"`   // 关注总数
	FollowerCount int64  `json:"follower_count"` // 粉丝总数
	ID            int64  `json:"id"`             // 用户id
	IsFollow      bool   `json:"is_follow"`      // true-已关注，false-未关注
	Name          string `json:"name"`
}

type InfoReq struct {
	UserId int64 `form:"user_id,omitempty"`
}

type InfoRes struct {
	CommonResp
	User UserPO `json:"user"`
}

type RegisterRes struct {
	CommonResp
	UserId int64  `json:"user_id,omitempty"`
	Token  string `json:"token"`
}

type RegisterReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type FollowerListResp struct {
	CommonResp
	UserList []UserPO `json:"user_list"`
}

type FollowerListReq struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type FollowingListResp struct {
	CommonResp
	UserList []UserPO `json:"user_list"`
}

type FollowingListReq struct {
	UserId int64  `form:"user_id"`
	Token  string `form:"token"`
}

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type UserLoginRes struct {
	CommonResp
	UserId int64  `json:"user_id,omitempty"`
	Token  string `json:"token"`
}
